name: Code Quality
on:
  pull_request:
    types: [ assigned, opened ]
  workflow_dispatch:

jobs:
  code-quality:

    name: Code Quality

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php-versions: [ '5.6', '7.0', '7.1', '7.2', '7.3', '7.4', '8.0']

    steps:
      - name: "📥 Fetching Repository Contents"
        uses: actions/checkout@v2

      - name: "💽  Installing PHP, Composer"
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          coverage: none
          ini-values: display_errors = on, error_reporting = E_ALL
          tools: composer

      - name: "💽  Installing Composer Packages"
        run: composer install

      - name: "🧪 Code Quality Checks"
        run: composer wpcs-lint
